global_costmap:
#  global_frame: map
#  robot_base_frame: base_footprint

  global_inflation_layer:
    inflation_radius: 1.0
    cost_scaling_factor: 3.0

  global_obstacle_layer:
    max_obstacle_heihgt: 2.0
    obstacle_range: 2.5
    raytrace_range: 3.0
    unknown_threshold: 6
    mark_threshold: 0
    track_unknown_space: true
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      sensor_frame: base_scan
      data_type: LaserScan
      topic: scan
      marking: false
      clearing: false

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5
  rolling_window: false

  static_map: true
 
  plugins:  
    - {name: map_layer, type: "costmap_2d::StaticLayer"}
    - {name: global_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: global_inflation_layer, type: "costmap_2d::InflationLayer"}
